### ISSUE TITLE
JOSS todo list

### ISSUE THREAD

**Issue by navidcy** [FourierFlows/FourierFlows.jl#141]
This is a proposed list for things we should implement before we announce the code in an open source journal, e.g., JOSS

- [x] GPU
- [x] Full GPU functionality on all modules
- [ ] 3D grid + 3DNavierStokes Module
- [x] Full Docs
- [x] Examples (w/ Literate.jl) that include animations where appropriate
- [ ] Choose 3 problems to demonstrate the code's capabilities (CPU, GPU, MPI).

As a maybes:
- [ ] MPI
- [ ] Field Abstraction; #129 
- [ ] use DifferentialEquations.jl for time integration (?)
- [ ] TimeSteppers for NamedTuples (?)
- [ ] AdaptiveTimeStepping (?)
